version: "3.9"
services:
  mariadb:
    restart: always
    volumes:
      - /app/data/mariadb:/var/lib/mysql
    expose:
      - 3306
  mongodb:
    restart: always
    volumes:
      - /app/data/mongodb:/data/db
    expose:
      - 27017
  scraper:
    restart: always
  loader:
    restart: always
  data-quality-ai:
    restart: always