/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("compartor.java-spring-application-conventions")
}

dependencies {
    implementation(project(":common"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.mariadb.jdbc:mariadb-java-client:3.0.3")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation ("org.springframework.boot:spring-boot-starter-security")
    implementation ("org.springframework.security:spring-security-test")
    implementation("org.modelmapper.extensions:modelmapper-spring:1.1.0")
    implementation("io.jsonwebtoken:jjwt:0.9.1")
}

springBoot {
    mainClass.set("com.cypros.comparator.api.Application")
}