
name: Deploy to VPS

on: workflow_dispatch

permissions:
  contents: read

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker-context-create
        uses: ArwynFr/actions-docker-context@v2
        with:
          docker_host: 'ssh://debian@141.95.193.15'
          context_name: 'dev-server'
          use_context: 'true'
          ssh_cert: ${{ secrets.SSH_CERT }}
          ssh_key: ${{ secrets.SSH_KEY }}
      - run: docker-compose rm -sf loader api scraper
      - run: docker rmi -f comparator-backend_loader comparator-backend_api comparator-backend_scraper

  build:
    needs: clean
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: docker-context-create
      uses: ArwynFr/actions-docker-context@v2
      with:
         docker_host: 'ssh://debian@141.95.193.15'
         context_name: 'dev-server'
         ssh_cert: ${{ secrets.SSH_CERT }}
         ssh_key: ${{ secrets.SSH_KEY }}
    - run: docker-compose --context dev-server -f docker-compose.yml -f docker-compose-prod.yml build loader api scraper
    - run: docker-compose --context dev-server -f docker-compose.yml -f docker-compose-prod.yml up -d loader api scraper



